services:
  - type: web
    name: romantic-aniversary
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO_URL
        value: https://github.com/Leo-Domingos/romantic-aniversary.git
      - key: NEXT_PUBLIC_GITHUB_REPO_URL
        value: https://github.com/Leo-Domingos/romantic-aniversary.git 